### ISSUE TITLE
ヘッダーを表示

### ISSUE THREAD

**Issue by takeyu1013** [takeyu1013/qin-todo#16]
- [ ] #18
- [ ] #19

**Comment by moto-1985** [comment]
タスク、分けてくださりありがとうございます。コンポーネント作成してみます。ユーザーによりアイコンが違うのでsupabaseからデータとってきて表示するビジネスロジックまで作ります。まだディレクトリ構成が決まっていないのでとりあえず１つの.tsx内に表示もロジックも入れちゃいます。
