### ISSUE TITLE
Apple でログイン可能にする

### ISSUE THREAD

**Issue by Natch** [takeyu1013/qin-todo#55]
https://www.supabase.jp/docs/guides/auth/auth-apple
ちょっとお金かかるみたいなので、見送りたい…
<img width="1080" alt="スクリーンショット 2022-03-29 21 26 29" src="https://user-images.githubusercontent.com/67428664/160611352-b344e31d-d87f-42c9-9033-209d7de13b9f.png">

**Comment by takeyu1013** [comment]
結構お金がかかるので、Apple認証は見送ります。
